### ISSUE TITLE
restart_webapp does not work

### ISSUE THREAD

**Issue by SidGrundfos** [chaostoolkit-incubator/chaostoolkit-azure#82]
![image](https://user-images.githubusercontent.com/53938860/68390916-9cf7d100-0166-11ea-812b-ebe6f55f46fd.png)
is not working, I am getting some error

[36m[2019-11-07 13:36:26 DEBUG] [python:34][39m Activity 'restart-webb-app' loaded from 'c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py'
[36m[2019-11-07 13:36:26 DEBUG] [actions:53][39m Start restart_webapp: configuration='{'azure': {'subscription_id': 'xxx'}}', filter='where resourceGroup == 'GF-RG-Base-d' and name = 'gf-web-dynamicscfs-d-azwe''
[36m[2019-11-07 13:36:26 DEBUG] [activity:230][39m Activity failed
    Traceback (most recent call last):
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaoslib\provider\python.py", line 55, in run_python_activity
        return func(**arguments)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 57, in restart_webapp
        choice = __fetch_webapp_at_random(filter, configuration, secrets)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 133, in __fetch_webapp_at_random
        webapps = fetch_webapps(filter, configuration, secrets)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 118, in fetch_webapps
        webapps = fetch_resources(filter, RES_TYPE_WEBAPP, secrets, configuration)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\rgraph\resource_graph.py", line 13, in fetch_resources
        resources = client.resources(query)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\azure\mgmt\resourcegraph\operations\_resource_graph_client_operations.py", line 64, in resources
        raise models.ErrorResponseException(self._deserialize, response)
    azure.mgmt.resourcegraph.models._models_py3.ErrorResponseException: (BadRequest) Please provide below info when asking for support: timestamp = 2019-11-07T12:36:26.9590396Z, correlationId = 456f97ab-5b44-42e9-9b96-ad5b4ce504b1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaoslib\activity.py", line 223, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaoslib\provider\python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaoslib\provider\python.py", line 55, in run_python_activity
        return func(**arguments)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 57, in restart_webapp
        choice = __fetch_webapp_at_random(filter, configuration, secrets)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 133, in __fetch_webapp_at_random
        webapps = fetch_webapps(filter, configuration, secrets)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\webapp\actions.py", line 118, in fetch_webapps
        webapps = fetch_resources(filter, RES_TYPE_WEBAPP, secrets, configuration)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\chaosazure\rgraph\resource_graph.py", line 13, in fetch_resources
        resources = client.resources(query)
      File "c:\users\910329\appdata\local\programs\python\python38\lib\site-packages\azure\mgmt\resourcegraph\operations\_resource_graph_client_operations.py", line 64, in resources
        raise models.ErrorResponseException(self._deserialize, response)
    chaoslib.exceptions.ActivityFailed: azure.mgmt.resourcegraph.models._models_py3.ErrorResponseException: (BadRequest) Please provide below info when asking for support: timestamp =

**Comment by SidGrundfos** [comment]
Action: restart-webb-app
additional_properties is not a known attribute of class <class 'azure.mgmt.resourcegraph.models._models_py3.QueryRequest'> and will be ignored
[2019-11-07 15:13:37 ERROR]   => failed: azure.mgmt.resourcegraph.models._models_py3.ErrorResponseException: (BadRequest) Please provide below info when asking for support: timestamp = 2019-11-07T14:13:37.4742506Z, correlationId = da1975b5-b635-43ae-bde5-c531cac0e8e5.
